export const lexicon = {
	add: 'Προσθήκη',
	admin: 'Διαχείριση',
	cancel: 'Άκυρο',
	deadline: 'Λήξη παιχνιδιού',
	deadline_expired: 'Το παιχνίδι έχει λήξει.',
	delete: 'Διαγραφή',
	edit: 'Επεξεργασία',
	error: 'Προέκυψε σφάλμα. Ανανέωσε τη σελίδα και ξαναδοκίμασε.',
	hide: 'Απόκρυψη',
	login: 'Είσοδος',
	logout: 'Έξοδος',
	password: 'Συνθηματικό',
	password_wrong: 'Πληκτρολόγησες λανθασμένο συνθηματικό.',
	player_from: 'από',
	player_info: 'Καταχώρισε τον κωδικό του παίκτη.',
	player_warning: 'Δεν βρέθηκε παίκτης με αυτό τον κωδικό.',
	question_mark: ';',
	reward_success: 'Πόντοι επιτυχίας',
	reward_conquest: 'Πόντοι κατάκτησης ανά λεπτό',
	select: '(Επίλεξε)',
	show: 'Εμφάνιση',
	submit: 'Υποβολή',
	success_simple: 'Επιτυχία',
	success_neutralization: 'Επιτυχία και εξουδετέρωση',
	success_conquest: 'Επιτυχία και κατάκτηση',
	station: 'Σταθμός',
	station_list: 'Σταθμοί',
	team_list: 'Ομάδες',
	title: 'The ΓΕΧΑ War',
};