export const lexicon = {
	admin: 'Διαχείριση',
	error: 'Προέκυψε σφάλμα. Ανανέωσε τη σελίδα και ξαναδοκίμασε.',
	deadline: 'Λήξη',
	login: 'Είσοδος',
	logout: 'Έξοδος',
	password: 'Συνθηματικό',
	player_from: 'από',
	player_info: 'Καταχώρισε τον κωδικό του παίκτη.',
	player_warning: 'Δεν βρέθηκε παίκτης με αυτό τον κωδικό.',
	reward_success: 'Πόντοι επιτυχίας',
	reward_conquest: 'Πόντοι κατάκτησης ανά λεπτό',
	select: '(Επίλεξε)',
	submit: 'Υποβολή',
	success_simple: 'Επιτυχία',
	success_neutralization: 'Επιτυχία και εξουδετέρωση',
	success_conquest: 'Επιτυχία και κατάκτηση',
	station: 'Σταθμός',
	title: 'The ΓΕΧΑ War',
	wrong_password: 'Πληκτρολόγησες λανθασμένο συνθηματικό.',
};