export const lexicon = {
	add: 'Προσθήκη',
	at: 'σε',
	admin: 'Διαχείριση',
	block: 'Αποκλεισμός',
	cancel: 'Άκυρο',
	candidate_count: 'Υποψήφιοι',
	delete: 'Διαγραφή',
	draw: 'Κλήρωση',
	edit: 'Επεξεργασία',
	error: 'Προέκυψε σφάλμα. Ανανέωσε τη σελίδα και ξαναδοκίμασε.',
	from: 'από',
	game_finished: 'Το παιχνίδι έχει λήξει!',
	game_pending: 'Το παιχνίδι δεν έχει ξεκινήσει!',
	game_start: 'Έναρξη παιχνιδιού',
	game_stop: 'Λήξη παιχνιδιού',
	hide: 'Απόκρυψη',
	history: 'Ιστορικό',
	id: 'Κωδικός',
	id_exists: 'Ο κωδικός αυτός δεν είναι διαθέσιμος.',
	import: 'Εισαγωγή',
	import_alert: 'Προσοχή! Όλοι οι αποθηκευμένοι παίκτες και οι συσχετισμένες επιτυχίες θα διαγραφούν!',
	import_error: 'Μη αποδεκτό κείμενο.',
	import_info: [
		'Κάθε γραμμή αποτελείται από τον κωδικό ενός παίκτη, το ονοματεπώνυμό του και το όνομα της ομάδας του.',
		'Τα στοιχεία χωρίζονται με τον χαρακτήρα tab.',
		'Οι κενές γραμμές αγνοούνται.',
	].join(' '),
	inspect: 'Επισκόπηση',
	login: 'Είσοδος',
	logout: 'Έξοδος',
	name: 'Όνομα',
	next: 'Συνέχεια',
	no: 'Όχι',
	password: 'Συνθηματικό',
	password_wrong: 'Πληκτρολόγησες λανθασμένο συνθηματικό.',
	place: 'Τοποθεσία',
	player_info: 'Καταχώρισε τον κωδικό του παίκτη.',
	player_list: 'Παίκτες',
	player_warning: 'Δεν βρέθηκε παίκτης με αυτό τον κωδικό.',
	point_histogram: 'Πόντοι',
	point_threshold: 'Ελάχιστοι πόντοι',
	position: 'Θέση',
	question_mark: ';',
	reward_conquest: 'Πόντοι κατάκτησης ανά λεπτό',
	reward_rate: 'Ρυθμός αύξησης αξίας πόντων ανά ώρα',
	reward_rate_begin: 'Αρχική αξία πόντων',
	reward_rate_end: 'Τελική αξία πόντων',
	reward_success: 'Πόντοι επιτυχίας',
	select: '(Επίλεξε)',
	show: 'Εμφάνιση',
	submit: 'Υποβολή',
	success_conquest: 'Επιτυχία και κατάκτηση',
	success_list: 'Επιτυχίες',
	success_neutralization: 'Επιτυχία και εξουδετέρωση',
	success_recent: 'Πρόσφατες επιτυχίες',
	success_simple: 'Επιτυχία',
	station: 'Σταθμός',
	station_list: 'Σταθμοί',
	team: 'Ομάδα',
	team_initial: 'Αρχική ομάδα',
	team_list: 'Ομάδες',
	title: 'The ΓΕΧΑ War',
	truncate: 'Εκκαθάριση',
	yes: 'Ναι',
};